language: python
python:
    - 2.7

install: 
    - sudo apt-get install libmysqlclient-dev
    - pip install -r requirements.txt

script: 
    - nosetests --verbose --cover-package=propertysuggester --with-coverage --cover-min-percentage=80