language: python
python:
    - 2.7
    - 3.5

install: 
    - sudo apt-get install libmysqlclient-dev
    - pip install -r requirements.txt

script:
    - coverage run --source propertysuggester -m pytest -v
    - flake8 . --max-line-length=100

after_success:
    - coverage report
    - coveralls debug
    - coveralls
