language: python
python:
    - 2.7
    - 3.5

install: 
    - sudo apt-get install libmysqlclient-dev
    - pip install -r requirements.txt
    - pip install codecov pytest-cov

script:
    - flake8 .
    - pytest -v --cov=propertysuggester

after_success:
    - codecov
